development:
  adapter: postgresql
  encoding: unicode
  database: nuke_clan_development
  pool: 5
  username: postgres
  password: password
test:
  adapter: postgresql
  encoding: unicode
  database: nuke_clan_test
  pool: 5
  username: postgres
  password: password
staging:
  adapter: postgresql
  encoding: unicode
  database: nuke_clan_staging
  pool: 5
  username: postgres
  password: password
production:
  adapter: postgresql
  encoding: unicode
  database: nuke_clan_production
  pool: 5
  username: postgres
  password: password